name: Check Template

on:
  workflow_call:

jobs:
  check-python:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Install algokit
        run: pipx install git+https://github.com/algorandfoundation/algokit-cli@feat/init_wizard_v2 --force

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Configure git
        shell: bash
        run: |
          # set git user and email as test invoke git
          git config --global user.email "actions@github.com" && git config --global user.name "github-actions"

      - name: Copy template (must complete without failing)
        shell: bash
        run: |
          set -o pipefail
          algokit init --template-url=. --template-url-ref="HEAD" -n test_run --UNSAFE-SECURITY-accept-template-url --no-bootstrap --no-git
